CREATE TABLE utenti (
    USERNAME VARCHAR(20) NOT NULL,
    PASSWORD CHAR(255) NOT NULL,

    CONSTRAINT PK_utenti PRIMARY KEY (USERNAME)
);

CREATE TABLE articoli (
    CODICE VARCHAR(3) NOT NULL,
    DESCRIZIONE VARCHAR(50),

    CONSTRAINT PK_articoli PRIMARY KEY (CODICE)
)